### ISSUE TITLE
Licensing nitrotracker's tobkit

### ISSUE THREAD

**Issue by asiekierka** [0xtob/nitrotracker#62]
While NitroTracker is licensed under the GPLv3 (and I see no strong problem with that), the 0xtob/tobkit repository is licensed under the LGPLv3. Trying to port over the tobkit components only present in NitroTracker (such as TabBoxes) to it would necessiate that such a version of tobkit be licensed under the GPLv3 as wel, which might be less than comfortable for potential users of the library.

In essence, what I'm requesting is to inquire whether or not the tobkit/ sub-directory could be relicensed under the LGPLv3 (or perhaps something even more liberal - that is up to you as the copyright owner) to match the existing, standalone, incomplete rewrite of tobkit.

**Comment by 0xtob** [comment]
Yes, absolutely! I guess we could just put a look license file in this
directory and it would apply to all files below it?

**Comment by asiekierka** [comment]
Technically, the ideal way to license a piece of software is to include a copyright notice in every file clearly stating which license it belongs under (the GNU project has some templates; it's crucial, as say, LGPLv3+ differs from LGPLv3 in that regard only), in addition to a license file with the piece of software. Also, I assume you're the sole rightsholder to that code, as otherwise there could be issues with relicensing parts you don't perhaps own.

**Comment by 0xtob** [comment]
Good point! I think LGPL is a bit too restrictive, so I decided to apply the Apache 2.0 license to this subdirectory (e239b197d4b178684de288b89fce7e1a5a1c4fc0). I should apply it to the standalone tobkit as well actually.
