### ISSUE TITLE
How to install in Nintendo 3DS?

### ISSUE THREAD

**Issue by Francisco2021521** [0xtob/nitrotracker#64]
How do I install this on Nintendo 3DS? (My 3DS is hacked and has CFW running. Any instructions on how to get it to run on it?)

**Comment by 0xtob** [comment]
It works on 3DS using TwilightMenu++. Btw, I recommend using this version of NitroTracker: https://github.com/asiekierka/nitrotracker

**Comment by Francisco2021521** [comment]
Thank you so much! Found out how to do it, used the NitrousTracker fork though, works just fine! :)
